#!/usr/bin/env bash
set -euo pipefail

usage() {
    echo "Usage: git fixup <commit>"
}

# If no arguments were passed, print the usage instructions
if [[ $# -eq 0 ]]; then
  usage
  exit 1
fi

# Read the commit ID from the script arguments, defaulting to an empty string
COMMIT="${1:-}"

# If the commit ID has not been specified, print usage instructions and exit
if [ -z "$COMMIT" ]; then
  usage
  exit 1
fi

git commit --fixup "$COMMIT"
