#!/usr/bin/env bash
set -euo pipefail

usage() {
    local command="$(basename "$0")"
    echo "Usage: $command <base> <feature>"
    echo ""
    echo "Rebase the commits from the feature branch at the point where it diverged from the base branch"
}

# If no arguments were passed, print the usage instructions
if [[ $# -eq 0 ]]; then
  usage
  exit 1
fi

# Read the base and feature branches from the script arguments, defaulting to an empty string
BASE="${1:-}"
FEATURE="${2:-}"

# If either the base or feature branch has not been specified, print usage instructions and exit
if [[ -z "$BASE" || -z "$FEATURE" ]]; then
  usage
  exit 1
fi

git rebase --onto "$BASE" "$(git merge-base "$BASE" "$FEATURE")" "$FEATURE"
